## 服务
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: data
    port: 3306
    targetPort: 3306 # 应用端口
  - name: cluster
    port: 33061
    targetPort: 3306 # 组复制端口
  clusterIP: None
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  namespace: default
  name: mysql-route
spec:
  entryPoints:
  - mysql
  #tls:
  #  secretName: mysql-tls
  routes:
  - match: HostSNI(`*`) # 首页
    services:
    - name: mysql
      port: 3306
