## 入口路由
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  namespace: default
  name: mysql-route
spec:
  entryPoints:
  - mysql
  tls:
    secretName: mysql-tls
  routes:
  - match: HostSNI(`mysql.ls.com`) # 首页
    services:
    - name: mysql
      port: 3306