apiVersion: v1
kind: ConfigMap
metadata:
  name: php
  labels:
    app: php
data:
  htmldir: lishi/api/
  php.ini: |-
    [PHP]
    engine = On
    short_open_tag = Off  ; 短标签
    precision = 14
    ; 缓冲输出		
    output_buffering = 4096  ; 缓冲 4096 字节的输出之后才会把内容发送给 Web 服务器
    ; output_handler =
    ; url_rewriter.tags = "form="
    ; url_rewriter.hosts = ""
    ; 
    zlib.output_compression = Off
    ;zlib.output_compression_level = -1
    ;zlib.output_handler =
    implicit_flush = Off
    unserialize_callback_func =
    ;unserialize_max_depth = 4096
    serialize_precision = -1
    ; 安全
    open_basedir = /var/www/html ; 只能访问网站目录
    disable_functions = passthru,system,chroot,scandir,chgrp,chown,shell_exec,proc_open,proc_get_status,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server
    disable_classes =
    ; 真是路径
    ; ignore_user_abort = On  
    ; realpath_cache_size = 4096k  ; 真实路径缓存
    ; realpath_cache_ttl = 120
    ; zend 设置
    zend.enable_gc = On
    ;zend.multibyte = Off
    ;zend.script_encoding = ""
    zend.exception_ignore_args = On
    ; 
    expose_php = Off  ; 将此项设置为false即不会再header头输出PHP版本信息。
    ; 资源限制
    max_execution_time = 30   ; 最大执行时间
    max_input_time = 60
    ; max_input_nesting_level = 64
    max_input_vars = 100000
    memory_limit = 2048M  ; 单个进程可使用最大内存
    ; 错误处理
    error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT  ; 错误级别
    display_errors = Off  ; 生产环境中，我们应该禁止错误提示，如果是本地开发环境，可以设置为On。
    display_startup_errors = Off
    log_errors = On  ; 建议在关闭display_errors后能够把错误信息记录下来，便于查找服务器运行的原因。
    log_errors_max_len = 1024
    ignore_repeated_errors = Off
    ignore_repeated_source = Off
    report_memleaks = On
    ; error_log = php_errors.log ; 设置PHP错误日志存放的目录
    ; 数据控制
    variables_order = "GPCS"  ; 环境变量 get post cookie server
    request_order = "GP"  ; 全局变量顺序
    register_argc_argv = Off
    auto_globals_jit = On
    auto_prepend_file =
    auto_append_file =
    default_mimetype = "text/html"
    default_charset = "UTF-8"
    ; 上传设置
    file_uploads = On  ; 支持文件上传
    max_file_uploads = 20   ; 最大文件上传数
    upload_max_filesize = 2M   ; 上传文件最大大小
    post_max_size = 8M
    [Session]  ; 会话
    ; session.save_handler = files  ; 在实际应用中，应当将会话保存在内存中,如redis
    ; session.save_path = '127.0.0.1:3679'
    [opcache] ; 代码缓存
    ; opcache.enable=1  ; 开启opcache加速
    ; opcache.memory_consumption = 128  ; 缓存内存大小,超出默认使用文件缓存
    ; opcache.validate_timestamps = 0  ; 自动检查脚本变化
    ; opcache.revalidate_freq = 60  ; 更新缓存频率
# 内部服务端口
---
apiVersion: v1
kind: Service
metadata:
  name: swoole
  namespace: default
  labels:
    app: php
spec:
  sessionAffinity: ClientIP ## 开启了session保持
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 ## 10800秒,3小时
  ports:
    - port: 9501 # 容器端口
      # protocol: TCP
      targetPort: 9501 # 应用端口
  selector:
    app: php
---
apiVersion: apps/v1 # version
kind: Deployment
metadata:
  name: php
  namespace: default
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: registry.cn-beijing.aliyuncs.com/baoweikai/php ## php:fpm-alpine 自定义镜像
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9501
              # name: php
          command: [ "/bin/sh", "-c", "php /var/www/html/$(HTML_DIR)think swoole" ]
          env:
          - name: HTML_DIR
            valueFrom:
              configMapKeyRef:
                name: php
                key: htmldir
          ##拉取镜像时的用户认证,没有的时候注释掉这2行
          #imagePullSecrets:
          #- name: registrypullsecret
          volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: php-ini
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
      volumes:
        - name: html
          hostPath:
            path: /mnt/www
        - name: php-ini
          configMap:
            name: php
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  # namespace: default
  name: swoole-route
spec:
  #tls:
  #  - certResolver: default
  entryPoints:
    - https
  routes:
    - match: Host(`api.ls.com`) # 首页
      kind: Rule
      services:
        - name: swoole
          port: 9501
  tls:
    certResolver: default
    domains:
      - main: "ls.com"
        sans:
          - "api.ls.com"