# 持久卷申明
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: lnmp
  labels:
    app: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      apps: pv-nfs
# 持久卷
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    app: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.151.30.57
    path: /data/mysql