# you're doing. 2 代表版本
Vagrant.configure("2") do |config|
  config.vm.box = "cos7"
  config.vm.provider "hyperv" do |v|
    v.memory = 2048
    v.cpus = 2
  end
	
	servers = {
	    :master => '192.168.137.10',
	    :node1 => '192.168.137.11',
	    :node2 => '192.168.137.12',
	    :node3 => '192.168.137.13'
	}
	gateway_ip = '192.168.137.1'
	# systemctl restart network # centos7网络重载
	$script = <<-SCRIPT
		sed -i '$a IPADDR='$1 /etc/sysconfig/network-scripts/ifcfg-eth0
		sed -i 's/"dhcp"/"static"/g' /etc/sysconfig/network-scripts/ifcfg-eth0
		sed -i '$a NETMASK=255.255.255.0' /etc/sysconfig/network-scripts/ifcfg-eth0
		sed -i '$a GATEWAY='$2 /etc/sysconfig/network-scripts/ifcfg-eth0
		sed -i '$a DNS1='$2 /etc/sysconfig/network-scripts/ifcfg-eth0
		sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
		## sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
		systemctl restart sshd
		mkdir /mnt/k8s
		mkdir /mnt/www
		sed -i '$a //'$2'/www /mnt/www cifs username=Administrator,password=830415,rw,dir_mode=0777,file_mode=0777 0 0' /etc/fstab
		sed -i '$a //'$2'/k8s /mnt/k8s cifs username=Administrator,password=830415 0 0' /etc/fstab
		mount -a
		echo -e "huaren830415" | passwd --stdin vagrant ## 重置密码
		echo -e "huaren830415" | passwd --stdin root ## 重置密码
		## systemctl restart network ## 重启网络配置
	SCRIPT
	# nmcli d reapply eth0
	servers.each do |server_name, server_ip|
		config.vm.define server_name, autostart: true do |server|
            # server.vm.network "private_network", ip: "server_ip"
			server.vm.host_name = server_name
			server.vm.provision "shell" do |s| 
				s.inline = $script
				s.args = [server_ip, gateway_ip]
			end
		end
	end
end
