version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - /D/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /D/www:/var/html
      - /D/docker/nginx:/var/log/nginx
      - /D/docker/etc/nginx/vhost:/etc/nginx/vhost
    networks:
      - net
    ports:
      - 80:80
      - 443:443
    command:
      - nginx
  php1:
    image: php
    volumes:
      - /D/docker/php/php-fpm.conf:/usr/local/php/php-fpm.conf
      - /D/www:/var/www/html
    ports:
      - 9001:9000
      - 9501:9501
    networks:
      - net
  php2:
    image: php
    volumes:
      - /D/docker/php/php-fpm.conf:/usr/local/php/php-fpm.conf       
      - /D/www:/var/www/html
    ports:
      - 9002:9000
      - 9501:9501
    networks:
      - net
  redis:
    image: redis
    volumes:
      - /D/docker/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - net
    environment:
      - REDIS_PORT=6379
      - appendonly=yes 
      - requirepass=baoweikai

